### PR TITLE
Fix IndexOutOfBoundsException in HeaderStore

### LINKED ISSUE #39: IndexOutOfBoundsException in HeaderStore
I constantly get the following exception when RecyclerView's adapter calls `notifyItemChanged()` for an item that has never been shown. It seems to me that `HeaderStore.onItemRangeChanged()` shouldn't handle this event for items with position larger than `isHeaderByItemPosition.size()`.

```
    java.lang.IndexOutOfBoundsException: Invalid index 81, size is 6
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.set(ArrayList.java:481)
            at com.eowise.recyclerview.stickyheaders.HeaderStore.onItemRangeChanged(HeaderStore.java:219)
            at com.eowise.recyclerview.stickyheaders.StickyHeadersItemDecoration$AdapterDataObserver.onItemRangeChanged(StickyHeadersItemDecoration.java:140)
            at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:7503)
            at android.support.v7.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:4353)
            ...
```

### PR DESCRIPTION
**Pull request by MichaelRocks**
This pull requests fixes #39 by properly manipulating items in isHeaderByItemPosition list.

### CODE REVIEW

**Comment by leruaa** [comment]
Thanks !

**Comment by jenshult** [comment]
Hi, I'm pretty anxious to see this fix being included in a release not too far off into the future. Any thoughts on when this might be?

**Comment by Elshad** [comment]
Hi, you did not publish library in Gradle (last updated Feb 12, 2015) after this bug fix. Please update

**Comment by aried3r** [comment]
I'd also love to see a new version pushed, @acatinon. Thanks! :)

**Comment by aried3r** [comment]
@acatinon, I saw you deprecated the library a day after I wrote the previous message, do you think you could release a last version which includes the latest fixes until you find someone who wants to take over the project?

**Pull request merged**
